<?php

namespace Database\Seeders;

use App\Models\Book;
use App\Models\BookCopy;
use App\Models\Category;
use Illuminate\Database\Seeder;

class BookSeeder extends Seeder
{
  /**
   * Run the database seeds.
   * Generates 50+ books with realistic data across all categories
   */
  public function run(): void
  {
    $books = [
      // ==================== FIKSI (10 buku) ====================
      [
        'title' => 'Laskar Pelangi',
        'author' => 'Andrea Hirata',
        'category' => 'Fiksi',
        'description' => 'Novel inspiratif tentang perjuangan anak-anak Belitung untuk meraih pendidikan. Kisah persahabatan dan semangat pantang menyerah.',
        'rental_fee' => 5000,
        'copies' => 3,
        'times_borrowed' => rand(15, 50),
        'publisher' => 'Bentang Pustaka',
        'year' => 2005,
        'isbn' => '979-3062-79-7',
      ],
      [
        'title' => 'Bumi Manusia',
        'author' => 'Pramoedya Ananta Toer',
        'category' => 'Fiksi',
        'description' => 'Novel sejarah tentang kehidupan di era kolonial Belanda. Kisah cinta Minke dan Annelies.',
        'rental_fee' => 7000,
        'copies' => 2,
        'times_borrowed' => rand(20, 60),
        'publisher' => 'Lentera Dipantara',
        'year' => 2005,
        'isbn' => '9789799731234',
      ],
      [
        'title' => 'Tenggelamnya Kapal Van Der Wijck',
        'author' => 'Hamka',
        'category' => 'Fiksi',
        'description' => 'Kisah cinta tragis yang mempertanyakan adat dan tradisi Minangkabau.',
        'rental_fee' => 5000,
        'copies' => 3,
        'times_borrowed' => rand(10, 40),
        'publisher' => 'Gema Insani',
        'year' => 2017,
        'isbn' => '9786022503835',
      ],
      [
        'title' => 'Dilan 1990',
        'author' => 'Pidi Baiq',
        'category' => 'Fiksi',
        'description' => 'Kisah cinta romantis antara Milea dan Dilan di Bandung tahun 1990.',
        'rental_fee' => 5000,
        'copies' => 4,
        'times_borrowed' => rand(25, 70),
        'publisher' => 'Pastel Books',
        'year' => 2014,
        'isbn' => '9786027870413',
      ],
      [
        'title' => 'Perahu Kertas',
        'author' => 'Dee Lestari',
        'category' => 'Fiksi',
        'description' => 'Novel tentang mimpi, cinta, dan seni. Kisah Kugy dan Keenan.',
        'rental_fee' => 6000,
        'copies' => 3,
        'times_borrowed' => rand(15, 45),
        'publisher' => 'Bentang Pustaka',
        'year' => 2009,
        'isbn' => '9789791227780',
      ],
      [
        'title' => 'Ayat-Ayat Cinta',
        'author' => 'Habiburrahman El Shirazy',
        'category' => 'Fiksi',
        'description' => 'Kisah cinta Fahri di Mesir dengan latar belakang keislaman yang kuat.',
        'rental_fee' => 6000,
        'copies' => 3,
        'times_borrowed' => rand(20, 55),
        'publisher' => 'Republika',
        'year' => 2004,
        'isbn' => '9789793604022',
      ],
      [
        'title' => 'Negeri 5 Menara',
        'author' => 'Ahmad Fuadi',
        'category' => 'Fiksi',
        'description' => 'Kisah persahabatan dan perjuangan di pesantren Gontor.',
        'rental_fee' => 5000,
        'copies' => 3,
        'times_borrowed' => rand(15, 40),
        'publisher' => 'Gramedia Pustaka Utama',
        'year' => 2009,
        'isbn' => '9789792248616',
      ],
      [
        'title' => 'Supernova: Ksatria, Puteri, dan Bintang Jatuh',
        'author' => 'Dee Lestari',
        'category' => 'Fiksi',
        'description' => 'Novel fiksi ilmiah pertama dari seri Supernova yang fenomenal.',
        'rental_fee' => 7000,
        'copies' => 2,
        'times_borrowed' => rand(10, 35),
        'publisher' => 'Truedee',
        'year' => 2001,
        'isbn' => '9789791227025',
      ],
      [
        'title' => 'Pulang',
        'author' => 'Tere Liye',
        'category' => 'Fiksi',
        'description' => 'Kisah seorang konsultan keuangan yang menemukan jati dirinya.',
        'rental_fee' => 6000,
        'copies' => 3,
        'times_borrowed' => rand(18, 50),
        'publisher' => 'Republika',
        'year' => 2015,
        'isbn' => '9786020822129',
      ],
      [
        'title' => 'Harry Potter dan Batu Bertuah',
        'author' => 'J.K. Rowling',
        'category' => 'Fiksi',
        'description' => 'Petualangan Harry Potter pertama kali memasuki dunia sihir Hogwarts.',
        'rental_fee' => 6000,
        'copies' => 5,
        'times_borrowed' => rand(30, 80),
        'publisher' => 'Gramedia Pustaka Utama',
        'year' => 2000,
        'isbn' => '9786020305882',
      ],

      // ==================== NON-FIKSI (5 buku) ====================
      [
        'title' => 'Sapiens: Sejarah Singkat Umat Manusia',
        'author' => 'Yuval Noah Harari',
        'category' => 'Non-Fiksi',
        'description' => 'Eksplorasi sejarah manusia dari zaman prasejarah hingga modern.',
        'rental_fee' => 8000,
        'copies' => 2,
        'times_borrowed' => rand(15, 45),
        'publisher' => 'KPG (Kepustakaan Populer Gramedia)',
        'year' => 2011,
        'isbn' => '9786024248744',
      ],
      [
        'title' => 'Homo Deus',
        'author' => 'Yuval Noah Harari',
        'category' => 'Non-Fiksi',
        'description' => 'Masa depan umat manusia dan tantangan yang akan dihadapi.',
        'rental_fee' => 8000,
        'copies' => 2,
        'times_borrowed' => rand(10, 30),
        'publisher' => 'KPG (Kepustakaan Populer Gramedia)',
        'year' => 2015,
        'isbn' => '9786024810576',
      ],
      [
        'title' => '21 Lessons for the 21st Century',
        'author' => 'Yuval Noah Harari',
        'category' => 'Non-Fiksi',
        'description' => '21 pelajaran penting untuk menghadapi abad ke-21.',
        'rental_fee' => 8000,
        'copies' => 2,
        'times_borrowed' => rand(8, 25),
        'publisher' => 'Manulife',
        'year' => 2018,
        'isbn' => '9780525512172',
      ],
      [
        'title' => 'Educated',
        'author' => 'Tara Westover',
        'category' => 'Non-Fiksi',
        'description' => 'Memoir inspiratif tentang kekuatan pendidikan dan keberanian.',
        'rental_fee' => 7000,
        'copies' => 2,
        'times_borrowed' => rand(12, 35),
        'publisher' => 'Gramedia Pustaka Utama',
        'year' => 2018,
        'isbn' => '9786020646619',
      ],
      [
        'title' => 'Guns, Germs, and Steel',
        'author' => 'Jared Diamond',
        'category' => 'Non-Fiksi',
        'description' => 'Mengapa beberapa peradaban lebih maju dari yang lain.',
        'rental_fee' => 8000,
        'copies' => 2,
        'times_borrowed' => rand(8, 22),
        'publisher' => 'KPG',
        'year' => 1997,
        'isbn' => '9780393317558',
      ],

      // ==================== ANAK-ANAK (5 buku) ====================
      [
        'title' => 'Si Kancil dan Buaya',
        'author' => 'Cerita Rakyat Indonesia',
        'category' => 'Anak-Anak',
        'description' => 'Dongeng klasik tentang kecerdikan Si Kancil.',
        'rental_fee' => 3000,
        'copies' => 5,
        'times_borrowed' => rand(20, 60),
        'publisher' => 'Bintang Indonesia',
        'year' => 2010,
        'isbn' => '9786022181552', // Placeholder valid format
      ],
      [
        'title' => 'Petualangan Timun Mas',
        'author' => 'Cerita Rakyat Jawa',
        'category' => 'Anak-Anak',
        'description' => 'Kisah gadis pemberani yang mengalahkan raksasa jahat.',
        'rental_fee' => 3000,
        'copies' => 4,
        'times_borrowed' => rand(18, 50),
        'publisher' => 'Erlangga for Kids',
        'year' => 2015,
        'isbn' => '9786022521198',
      ],
      [
        'title' => 'Malin Kundang',
        'author' => 'Cerita Rakyat Sumatra',
        'category' => 'Anak-Anak',
        'description' => 'Legenda anak durhaka dari Sumatra Barat.',
        'rental_fee' => 3000,
        'copies' => 4,
        'times_borrowed' => rand(15, 45),
        'publisher' => 'Balai Pustaka',
        'year' => 2008,
        'isbn' => '9789794071748',
      ],
      [
        'title' => 'Keong Emas',
        'author' => 'Cerita Rakyat Jawa',
        'category' => 'Anak-Anak',
        'description' => 'Kisah putri yang dikutuk menjadi keong emas.',
        'rental_fee' => 3000,
        'copies' => 4,
        'times_borrowed' => rand(12, 40),
        'publisher' => 'Bintang Indonesia',
        'year' => 2012,
        'isbn' => '9786029532548',
      ],
      [
        'title' => 'Bawang Merah Bawang Putih',
        'author' => 'Cerita Rakyat Indonesia',
        'category' => 'Anak-Anak',
        'description' => 'Cerita tentang kebaikan selalu menang melawan kejahatan.',
        'rental_fee' => 3000,
        'copies' => 5,
        'times_borrowed' => rand(20, 55),
        'publisher' => 'Serba Jaya',
        'year' => 2014,
        'isbn' => '9786028275323',
      ],

      // ==================== PENDIDIKAN (5 buku) ====================
      [
        'title' => 'Matematika SMA Kelas 12',
        'author' => 'Tim Penyusun Kemendikbud',
        'category' => 'Pendidikan',
        'description' => 'Buku pelajaran matematika untuk siswa SMA kelas 12.',
        'rental_fee' => 4000,
        'copies' => 6,
        'times_borrowed' => rand(25, 70),
        'publisher' => 'Kemendikbud',
        'year' => 2018,
        'isbn' => '9786022829980',
      ],
      [
        'title' => 'Bahasa Indonesia untuk Pemula',
        'author' => 'Dr. Ahmad Sudrajat',
        'category' => 'Pendidikan',
        'description' => 'Panduan belajar bahasa Indonesia yang baik dan benar.',
        'rental_fee' => 4000,
        'copies' => 3,
        'times_borrowed' => rand(12, 35),
        'publisher' => 'Pustaka Pelajar',
        'year' => 2019,
        'isbn' => '9786022299880',
      ],
      [
        'title' => 'Fisika Dasar untuk Universitas',
        'author' => 'Prof. Dr. Sutrisno',
        'category' => 'Pendidikan',
        'description' => 'Buku fisika dasar untuk mahasiswa tahun pertama.',
        'rental_fee' => 5000,
        'copies' => 4,
        'times_borrowed' => rand(18, 50),
        'publisher' => 'ITB Press',
        'year' => 1997,
        'isbn' => '9798001004',
      ],
      [
        'title' => 'Kimia Organik',
        'author' => 'Dr. Fessenden',
        'category' => 'Pendidikan',
        'description' => 'Panduan lengkap kimia organik untuk perguruan tinggi.',
        'rental_fee' => 6000,
        'copies' => 3,
        'times_borrowed' => rand(10, 30),
        'publisher' => 'Erlangga',
        'year' => 1999,
        'isbn' => '9797810756',
      ],
      [
        'title' => 'TOEFL Preparation Guide',
        'author' => 'Educational Testing Service',
        'category' => 'Pendidikan',
        'description' => 'Panduan lengkap persiapan tes TOEFL.',
        'rental_fee' => 5000,
        'copies' => 4,
        'times_borrowed' => rand(20, 55),
        'publisher' => 'Barron\'s Educational Series',
        'year' => 2020,
        'isbn' => '9781438011875',
      ],

      // ==================== KOMIK & MANGA (6 buku) ====================
      [
        'title' => 'One Piece Vol. 1',
        'author' => 'Eiichiro Oda',
        'category' => 'Komik & Manga',
        'description' => 'Petualangan Monkey D. Luffy mencari harta karun One Piece.',
        'rental_fee' => 3000,
        'copies' => 5,
        'times_borrowed' => rand(40, 100),
        'publisher' => 'Elex Media Komputindo',
        'year' => 1997,
        'isbn' => '9781569319017',
      ],
      [
        'title' => 'Naruto Vol. 1',
        'author' => 'Masashi Kishimoto',
        'category' => 'Komik & Manga',
        'description' => 'Kisah ninja muda Naruto Uzumaki mengejar mimpinya.',
        'rental_fee' => 3000,
        'copies' => 4,
        'times_borrowed' => rand(35, 90),
        'publisher' => 'Elex Media Komputindo',
        'year' => 2003,
        'isbn' => '9781569319000',
      ],
      [
        'title' => 'Attack on Titan Vol. 1',
        'author' => 'Hajime Isayama',
        'category' => 'Komik & Manga',
        'description' => 'Pertempuran umat manusia melawan para titan pemakan manusia.',
        'rental_fee' => 3500,
        'copies' => 4,
        'times_borrowed' => rand(30, 80),
        'publisher' => 'Elex Media Komputindo',
        'year' => 2012,
        'isbn' => '9781612620244',
      ],
      [
        'title' => 'Dragon Ball Vol. 1',
        'author' => 'Akira Toriyama',
        'category' => 'Komik & Manga',
        'description' => 'Petualangan Son Goku mencari bola naga legendaris.',
        'rental_fee' => 3000,
        'copies' => 3,
        'times_borrowed' => rand(25, 65),
        'publisher' => 'Elex Media Komputindo',
        'year' => 2003,
        'isbn' => '9781569319208',
      ],
      [
        'title' => 'Demon Slayer Vol. 1',
        'author' => 'Koyoharu Gotouge',
        'category' => 'Komik & Manga',
        'description' => 'Tanjiro menjadi pemburu iblis untuk menyelamatkan adiknya.',
        'rental_fee' => 3500,
        'copies' => 4,
        'times_borrowed' => rand(35, 85),
        'publisher' => 'Elex Media Komputindo',
        'year' => 2018,
        'isbn' => '9781974700523',
      ],
      [
        'title' => 'Doraemon Vol. 1',
        'author' => 'Fujiko F. Fujio',
        'category' => 'Komik & Manga',
        'description' => 'Robot kucing dari masa depan dengan kantong ajaib.',
        'rental_fee' => 3000,
        'copies' => 5,
        'times_borrowed' => rand(30, 75),
        'publisher' => 'Elex Media Komputindo',
        'year' => 1990,
        'isbn' => '9789792015515', // Estimasi
      ],

      // ==================== PENGEMBANGAN DIRI (5 buku) ====================
      [
        'title' => 'Atomic Habits',
        'author' => 'James Clear',
        'category' => 'Pengembangan Diri',
        'description' => 'Panduan membangun kebiasaan baik dan menghilangkan yang buruk.',
        'rental_fee' => 6000,
        'copies' => 4,
        'times_borrowed' => rand(35, 90),
        'publisher' => 'Gramedia Pustaka Utama',
        'year' => 2018,
        'isbn' => '9780735211292',
      ],
      [
        'title' => 'Sebuah Seni Untuk Bersikap Bodo Amat',
        'author' => 'Mark Manson',
        'category' => 'Pengembangan Diri',
        'description' => 'Pendekatan berbeda untuk menjalani hidup yang lebih baik.',
        'rental_fee' => 6000,
        'copies' => 4,
        'times_borrowed' => rand(30, 80),
        'publisher' => 'Grasindo',
        'year' => 2016,
        'isbn' => '9780062457714',
      ],
      [
        'title' => 'Mindset: The New Psychology of Success',
        'author' => 'Carol S. Dweck',
        'category' => 'Pengembangan Diri',
        'description' => 'Bagaimana pola pikir mempengaruhi kesuksesan kita.',
        'rental_fee' => 6000,
        'copies' => 3,
        'times_borrowed' => rand(20, 55),
        'publisher' => 'Ballantine Books',
        'year' => 2006,
        'isbn' => '9780345472328',
      ],
      [
        'title' => 'The 7 Habits of Highly Effective People',
        'author' => 'Stephen R. Covey',
        'category' => 'Pengembangan Diri',
        'description' => '7 kebiasaan orang-orang yang sangat efektif.',
        'rental_fee' => 7000,
        'copies' => 3,
        'times_borrowed' => rand(25, 65),
        'publisher' => 'Simon & Schuster',
        'year' => 1989,
        'isbn' => '9780743269513',
      ],
      [
        'title' => 'Deep Work',
        'author' => 'Cal Newport',
        'category' => 'Pengembangan Diri',
        'description' => 'Aturan untuk fokus sukses di dunia yang penuh distraksi.',
        'rental_fee' => 6000,
        'copies' => 3,
        'times_borrowed' => rand(15, 45),
        'publisher' => 'Grand Central Publishing',
        'year' => 2016,
        'isbn' => '9781455586691',
      ],

      // ==================== BISNIS (5 buku) ====================
      [
        'title' => 'Rich Dad Poor Dad',
        'author' => 'Robert Kiyosaki',
        'category' => 'Bisnis',
        'description' => 'Pelajaran keuangan dari dua perspektif ayah yang berbeda.',
        'rental_fee' => 6000,
        'copies' => 3,
        'times_borrowed' => rand(30, 75),
        'publisher' => 'Plata Publishing',
        'year' => 1997,
        'isbn' => '9781612680194',
      ],
      [
        'title' => 'The Psychology of Money',
        'author' => 'Morgan Housel',
        'category' => 'Bisnis',
        'description' => 'Pelajaran tentang kekayaan, keserakahan, dan kebahagiaan.',
        'rental_fee' => 7000,
        'copies' => 3,
        'times_borrowed' => rand(25, 65),
        'publisher' => 'Harriman House',
        'year' => 2020,
        'isbn' => '9780857197689',
      ],
      [
        'title' => 'Zero to One',
        'author' => 'Peter Thiel',
        'category' => 'Bisnis',
        'description' => 'Catatan tentang startup dan cara membangun masa depan.',
        'rental_fee' => 7000,
        'copies' => 2,
        'times_borrowed' => rand(18, 50),
        'publisher' => 'Crown Currency',
        'year' => 2014,
        'isbn' => '9780804139298',
      ],
      [
        'title' => 'The Lean Startup',
        'author' => 'Eric Ries',
        'category' => 'Bisnis',
        'description' => 'Metode untuk membuat produk dan bisnis yang sukses.',
        'rental_fee' => 7000,
        'copies' => 2,
        'times_borrowed' => rand(15, 45),
        'publisher' => 'Crown Currency',
        'year' => 2011,
        'isbn' => '9780307887894',
      ],
      [
        'title' => 'Think and Grow Rich',
        'author' => 'Napoleon Hill',
        'category' => 'Bisnis',
        'description' => 'Klasik tentang rahasia sukses finansial.',
        'rental_fee' => 5000,
        'copies' => 3,
        'times_borrowed' => rand(22, 60),
        'publisher' => 'The Ralston Society',
        'year' => 1937,
        'isbn' => '9781585424337',
      ],

      // ==================== SEJARAH (4 buku) ====================
      [
        'title' => 'Sejarah Indonesia Modern',
        'author' => 'M.C. Ricklefs',
        'category' => 'Sejarah',
        'description' => 'Sejarah Indonesia dari abad ke-16 hingga sekarang.',
        'rental_fee' => 7000,
        'copies' => 2,
        'times_borrowed' => rand(10, 30),
        'publisher' => 'Gadjah Mada University Press',
        'year' => 2008,
        'isbn' => '9780804723055',
      ],
      [
        'title' => 'Indonesia: Sejarah & Budaya',
        'author' => 'Prof. Dr. Koentjaraningrat',
        'category' => 'Sejarah',
        'description' => 'Kajian mendalam tentang sejarah dan budaya Indonesia.',
        'rental_fee' => 6000,
        'copies' => 2,
        'times_borrowed' => rand(8, 25),
        'publisher' => 'Djambatan',
        'year' => 2004,
        'isbn' => '9789794282366', // Estimasi
      ],
      [
        'title' => 'Nusantara: Sejarah Indonesia',
        'author' => 'Bernard H.M. Vlekke',
        'category' => 'Sejarah',
        'description' => 'Sejarah lengkap nusantara dari masa kuno.',
        'rental_fee' => 7000,
        'copies' => 2,
        'times_borrowed' => rand(6, 20),
        'publisher' => 'KPG',
        'year' => 2008,
        'isbn' => '9789799103093',
      ],
      [
        'title' => 'Dari Penjara ke Penjara',
        'author' => 'Tan Malaka',
        'category' => 'Sejarah',
        'description' => 'Autobiografi tokoh pergerakan kemerdekaan Indonesia.',
        'rental_fee' => 5000,
        'copies' => 2,
        'times_borrowed' => rand(8, 22),
        'publisher' => 'Tempo',
        'year' => 2008,
        'isbn' => '9789799635747',
      ],

      // ==================== KESEHATAN (4 buku) ====================
      [
        'title' => 'Hidup Sehat dengan Pola Makan',
        'author' => 'Dr. Tan Shot Yen',
        'category' => 'Kesehatan',
        'description' => 'Panduan pola makan sehat untuk kehidupan lebih baik.',
        'rental_fee' => 5000,
        'copies' => 3,
        'times_borrowed' => rand(15, 40),
        'publisher' => 'Gramedia Pustaka Utama',
        'year' => 2015,
        'isbn' => '9786020619040', // Estimasi
      ],
      [
        'title' => 'Why We Sleep',
        'author' => 'Matthew Walker',
        'category' => 'Kesehatan',
        'description' => 'Ilmu di balik tidur dan pentingnya untuk kesehatan.',
        'rental_fee' => 6000,
        'copies' => 2,
        'times_borrowed' => rand(12, 35),
        'publisher' => 'Scribner',
        'year' => 2017,
        'isbn' => '9781501144318',
      ],
      [
        'title' => 'The Body: A Guide for Occupants',
        'author' => 'Bill Bryson',
        'category' => 'Kesehatan',
        'description' => 'Panduan lengkap tentang tubuh manusia.',
        'rental_fee' => 7000,
        'copies' => 2,
        'times_borrowed' => rand(10, 30),
        'publisher' => 'Doubleday',
        'year' => 2019,
        'isbn' => '9780385539302',
      ],
      [
        'title' => 'Brain Rules',
        'author' => 'John Medina',
        'category' => 'Kesehatan',
        'description' => '12 prinsip untuk bertahan dan berkembang.',
        'rental_fee' => 6000,
        'copies' => 2,
        'times_borrowed' => rand(8, 25),
        'publisher' => 'Pear Press',
        'year' => 2008,
        'isbn' => '9780979777707',
      ],

      // ==================== SASTRA KLASIK (4 buku) ====================
      [
        'title' => 'Siti Nurbaya',
        'author' => 'Marah Rusli',
        'category' => 'Sastra Klasik',
        'description' => 'Kisah cinta yang terhalang perjodohan adat Minangkabau.',
        'rental_fee' => 5000,
        'copies' => 2,
        'times_borrowed' => rand(12, 35),
        'publisher' => 'Balai Pustaka',
        'year' => 1922,
        'isbn' => '9786022600044', // Estimasi
      ],
      [
        'title' => 'Layar Terkembang',
        'author' => 'Sutan Takdir Alisjahbana',
        'category' => 'Sastra Klasik',
        'description' => 'Novel tentang emansipasi wanita Indonesia.',
        'rental_fee' => 5000,
        'copies' => 2,
        'times_borrowed' => rand(8, 25),
        'publisher' => 'Balai Pustaka',
        'year' => 1936,
        'isbn' => '9789794071663', // Estimasi
      ],
      [
        'title' => 'Azab dan Sengsara',
        'author' => 'Merari Siregar',
        'category' => 'Sastra Klasik',
        'description' => 'Novel pertama berbahasa Indonesia.',
        'rental_fee' => 5000,
        'copies' => 2,
        'times_borrowed' => rand(6, 20),
        'publisher' => 'Balai Pustaka',
        'year' => 1920,
        'isbn' => '9789794071670', // Estimasi
      ],
      [
        'title' => 'Atheis',
        'author' => 'Achdiat K. Mihardja',
        'category' => 'Sastra Klasik',
        'description' => 'Pergulatan iman seorang pemuda Indonesia.',
        'rental_fee' => 5000,
        'copies' => 2,
        'times_borrowed' => rand(8, 22),
        'publisher' => 'Balai Pustaka',
        'year' => 1949,
        'isbn' => '9789794071687', // Estimasi
      ],

      // ==================== SAINS & TEKNOLOGI (4 buku) ====================
      [
        'title' => 'A Brief History of Time',
        'author' => 'Stephen Hawking',
        'category' => 'Sains & Teknologi',
        'description' => 'Penjelasan populer tentang kosmologi dan alam semesta.',
        'rental_fee' => 7000,
        'copies' => 2,
        'times_borrowed' => rand(15, 40),
        'publisher' => 'Bantam Books',
        'year' => 1988,
        'isbn' => '9780553380163',
      ],
      [
        'title' => 'The Code Breaker',
        'author' => 'Walter Isaacson',
        'category' => 'Sains & Teknologi',
        'description' => 'Kisah CRISPR dan masa depan rekayasa genetika.',
        'rental_fee' => 8000,
        'copies' => 2,
        'times_borrowed' => rand(10, 30),
        'publisher' => 'Simon & Schuster',
        'year' => 2021,
        'isbn' => '9781982115852',
      ],
      [
        'title' => 'Clean Code',
        'author' => 'Robert C. Martin',
        'category' => 'Sains & Teknologi',
        'description' => 'Panduan menulis kode yang bersih dan dapat dipelihara.',
        'rental_fee' => 8000,
        'copies' => 3,
        'times_borrowed' => rand(20, 55),
        'publisher' => 'Prentice Hall',
        'year' => 2008,
        'isbn' => '9780132350884',
      ],
      [
        'title' => 'The Pragmatic Programmer',
        'author' => 'David Thomas & Andrew Hunt',
        'category' => 'Sains & Teknologi',
        'description' => 'Dari pemula menjadi programmer master.',
        'rental_fee' => 8000,
        'copies' => 3,
        'times_borrowed' => rand(18, 50),
        'publisher' => 'Addison-Wesley Professional',
        'year' => 1999,
        'isbn' => '9780201616224',
      ],

      // ==================== AGAMA (3 buku) ====================
      [
        'title' => 'Tafsir Al-Quran Al-Azhar Jilid 1',
        'author' => 'Buya Hamka',
        'category' => 'Agama',
        'description' => 'Tafsir Al-Quran karya ulama besar Indonesia.',
        'rental_fee' => 5000,
        'copies' => 3,
        'times_borrowed' => rand(15, 40),
        'publisher' => 'Gema Insani',
        'year' => 1967,
        'isbn' => '9786022502395', // Estimasi
      ],
      [
        'title' => 'Ihya Ulumuddin',
        'author' => 'Imam Al-Ghazali',
        'category' => 'Agama',
        'description' => 'Karya monumental tentang ilmu-ilmu agama.',
        'rental_fee' => 6000,
        'copies' => 2,
        'times_borrowed' => rand(10, 30),
        'publisher' => 'Republika',
        'year' => 2011,
        'isbn' => '9786028997324', // Estimasi
      ],
      [
        'title' => 'Fiqih Sunnah',
        'author' => 'Sayyid Sabiq',
        'category' => 'Agama',
        'description' => 'Panduan lengkap fiqih berdasarkan sunnah Nabi.',
        'rental_fee' => 5000,
        'copies' => 3,
        'times_borrowed' => rand(12, 35),
        'publisher' => 'Pena Pundi Aksara',
        'year' => 2006,
        'isbn' => '9789793033525', // Estimasi
      ],
    ];

    foreach ($books as $bookData) {
      // Get category
      $category = Category::where('name', $bookData['category'])->first();

      if (!$category) {
        continue;
      }

      // Create or update book
      $book = Book::updateOrCreate(
        ['title' => $bookData['title']],
        [
          'author' => $bookData['author'],
          'category_id' => $category->id,
          'description' => $bookData['description'],
          'rental_fee' => $bookData['rental_fee'],
          'total_copies' => $bookData['copies'],
          'available_copies' => $bookData['copies'],
          'times_borrowed' => $bookData['times_borrowed'] ?? 0,
          'publisher' => $bookData['publisher'] ?? 'Penerbit Umum',
          'year' => $bookData['year'] ?? rand(2010, 2023),
          'isbn' => $bookData['isbn'] ?? fake()->isbn13(),
          'book_price' => $bookData['rental_fee'] * 20, // Simulasi harga beli
        ]
      );

      // Create copies if book was just created
      if ($book->wasRecentlyCreated) {
        for ($i = 1; $i <= $bookData['copies']; $i++) {
          BookCopy::create([
            'book_id' => $book->id,
            'copy_code' => sprintf('BK%03d-C%02d', $book->id, $i),
            'status' => 'available',
            'notes' => null,
          ]);
        }
      }
    }
  }
}
